// Thin-content redirects list (originally 2026-04-17, cleared 2026-05-04).
// All 428 slugs listed here had their .md files regenerated by subsequent SEO
// content waves — they are live published pages and must NOT redirect.
// List cleared to stop the 308 → /blog mass-redirect that was burying 427 pages.
//
// Only add a slug here if the corresponding src/content/blog/<slug>.md has been
// physically deleted AND you want external links to fall back to /blog.
export const deletedBlogSlugs: readonly string[] = [] as const;
